### PR TITLE
Multiple keys

### LINKED ISSUE #5: Add option to change key press to different value when auto is used
Currently the "Auto" mode itterates through the number of pages and goes to the next page using the down arrow. 
This may not work for all cases.
An option should be added to the GUI to allow using different keys presses or combinations or mouse input.

### PR DESCRIPTION
**Pull request by ArielMAJ**
Resolves #5 (partially?).

Lots of changes to the GUI here. Hope you like it!

### CODE REVIEW

**Comment by ArielMAJ** [comment]
This force-push was so the pull-request would have your most recent changes (I rebased my branch from master).

**Comment by Leah9** [comment]
Capture

**Comment by Leah9** [comment]
Not sure what happened here i think i should  accept incoming change ?

**Comment by ArielMAJ** [comment]
Yeah, weird. But yes it incoming change is the most recent implementation. Maybe rebasing here wasn't a good idea (?)

**Comment by Leah9** [comment]
Its all working, no issue :D

Thank-you so much !

**Pull request merged**
