### PR TITLE
Iterative feedback

### LINKED ISSUE #1: Implement feedback in GUI rather than console
Implement feedback in GUI rather than console.
e.g. count-down to get box dimensions

### PR DESCRIPTION
**Pull request by ArielMAJ**
Resolve #1 
I started implementing some of the feedback in GUI. Instead of countdown there will be pop ups and you just have to position your mouse and press enter each time (to close the pop up and resume getting the current mouse position).

Does that work or would you prefer a countdown in the popup instead?

### CODE REVIEW

**Comment by Leah9** [comment]
That sounds really good.

Im still learning git / github and i dont know what to do ? I have created a new testing branch and changed some code to remove the need for pyscreenshot etc.

What order do i merge mine yours in together ?

**Comment by ArielMAJ** [comment]
Don't worry, I'm also not really proficient at all in git lol.
I spent quite a while creating branches of my branches to learn how to merge your (earlier) changes to mine locally. From what I read you gotta read both files, compare the changes and decide what to keep (by erasing the files/lines that you don't want). From there you create a new commit with the changes you want to keep.
It seems both of us made quite a few changes, so this might be tricky to merge.

**Comment by ArielMAJ** [comment]
I'm not really sure how to do it on Github though, as I've never merged branches before either. Do it however you prefer or find easier. If anything goes wrong, we still should have backups locally to try and fix things.

**Comment by Leah9** [comment]
Can you do another pull from the main branch , merge your changes with it and then create a new pull request please ?

I think the biggest issue is renaming of the MainWndow.py file

**Comment by ArielMAJ** [comment]
Sure. I was also thinking that this would be the easiest too

**Comment by Leah9** [comment]
Really hope we can get this working :D

**Pull request closed without merging**
