### PR TITLE
ScreenShot naming is now based on current time.

### LINKED ISSUE #24: Images in the repository are overwritten when restarting the program (it restarts the counter).
TODO: Use len(glob(img*.png))

I'll probably implement this later

### PR DESCRIPTION
**Pull request by ArielMAJ**
Also commented out some 'print()'s (mainly related to self.image_no).

Resolves #24, but we still could see into making the image folder more organized as per https://github.com/Leah9/screengrab/issues/24#issuecomment-1129439640

### CODE REVIEW

**Comment by Leah9** [comment]
Capture

**Comment by ArielMAJ** [comment]
Keep the changes from image-names.

I also ran into this locally as well (i made these changes on top of the wrong branch and used git cherry pick on a new one). I hope this is the only conflict for you as well.

Lmk if you have any more questions

**Comment by ArielMAJ** [comment]
Actually,  i just realized something seems not right. I'll look into it a bit more before the merge.

**Comment by Leah9** [comment]
Thank you, I was just asking the tutor in college ha ha

**Comment by ArielMAJ** [comment]
This situation was actually a bit different from what I ran into. This conflict happened because of the previous merge (from the other pull resquest).

It's still looking a bit weird to me because it seems I merged master into my branch instead of having my branch merged into yours. I'm thinking maybe I should do changes locally and then force push so you can merge later (without this extra merge from yours to mine).

**Comment by Leah9** [comment]
Do you want to close this one and submit a new one later ?

Im in college so probably wont have another chance to look until this evening :)

**Comment by ArielMAJ** [comment]
Sure. I'll be sending another PR soon.

**Pull request closed without merging**
